<%@ Page Title="Module" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Module.aspx.cs" Inherits="BerkleyCollegeSystem.WebForm1" %>


<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <div class="row">
		<div class="col d-flex comfortaa-light text-sm">
			<div class="card flex-fill p-4 shadow">
				

                <div class="mb-2">
                    <h5><asp:Label ID="Label1" class="intro-rust" runat="server" Text="Module Details"></asp:Label></h5>
                    <hr />
                </div>

                <div class="form-group row mb-2">
                    <asp:Label ID="Label2" class="col-sm-2 col-form-label" runat="server" for="TextBoxName" Text="Module Name * : "></asp:Label>
                    <div class="col-sm-10">
                        <asp:TextBox class="form-control font-small" ID="TextBoxName" runat="server" MaxLength="50" required="true"></asp:TextBox>
                    </div>
                </div>

                <div class="form-group row mb-2">
                    <asp:Label ID="Label3" class="col-sm-2 col-form-label" runat="server" for="TextCreditHours" Text="Credit Hours * : "></asp:Label>
                    <div class="col-sm-10">
                        <asp:TextBox class="form-control font-small" ID="TextCreditHours" runat="server" MaxLength="9" pattern="[0-9]*" title="Please enter only numbers." required="true"></asp:TextBox>
                    </div>
                </div>

                <div class="form-group row mb-2">
                    <asp:Label ID="Label4" class="col-sm-2 col-form-label" runat="server" for="TextTotalDays" Text="Total Days * : "></asp:Label>
                    <div class="col-sm-10">
                        <asp:TextBox class="form-control font-small" ID="TextTotalDays" runat="server" MaxLength="9" pattern="[0-9]*" title="Please enter only numbers." required="true"></asp:TextBox>
                    </div>
                </div>
                
                <div>
                    <asp:TextBox ID="ModuleCode" runat="server" Visible ="false"></asp:TextBox>
                </div>
                

                <div class="mt-5 text-end">
                    <asp:Button ID="ButtonSubmit" runat="server" Text="Submit" class="btn btn-primary btn-lg px-4 font-small" OnClick="ButtonSubmit_Click"/>
                </div>
            
            </div>
        </div>
    </div>
    
    <div class="row mt-2">
		<div class="col d-flex">
			<div class="card flex-fill p-4 shadow">

				<div class="">
                    
                    <asp:GridView   ID="ModuleGridView" runat="server" DataKeyNames="Module Code" 
                                    OnRowDataBound="OnRowDataBound" 
                                    OnRowEditing="OnRowEditing" 
                                    OnRowCancelingEdit="OnRowCancelingEdit"  
                                    OnRowDeleting="OnRowDeleting" 
                                    EmptyDataText="No records has been added."  
                                    AutoGenerateEditButton="True" 
                                    AutoGenerateDeleteButton="True"
                                    class="table table-hover table-responsive border-0 comfortaa-light text-sm">
                        
                        <RowStyle CssClass="table-responsive table-hover opacity-75" />
                        
                    </asp:GridView>

                </div>
            
            </div>
        </div>
    </div>

</asp:Content>