/**
 * @author 19030709-Animesh Singh Basnet, 19031360-Pranamya Sharma, 19032186-Srijana Tamang
 */

package Opticalog.Main;

import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.UIManager;


public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form splash
     */
    public SplashScreen() {
        
        Font bauhaus =null, courier = null;
        
        // importing custom fonts
        try{
            bauhaus = Font.createFont(Font.TRUETYPE_FONT, new FileInputStream(new File("./src/Opticalog/Fonts/bauhaus.ttf"))).deriveFont(Font.BOLD, 16);
            courier = Font.createFont(Font.TRUETYPE_FONT, new FileInputStream(new File("./src/Opticalog/Fonts/cour.ttf"))).deriveFont(Font.BOLD, 11);
        } catch(Exception e){
            e.printStackTrace();
        } 
        
        // Setting default font for the components
        UIManager.put("Label.font",courier);

        initComponents();
        
        // Adding fonts to specific components
        loading_lbl.setFont(bauhaus);
        percentage_lbl.setFont(courier.deriveFont(Font.BOLD,14));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        percentage_lbl = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        randomtxt_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loading_lbl = new javax.swing.JLabel();
        version_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opticalog");
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 50, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        percentage_lbl.setForeground(new java.awt.Color(230, 236, 239));
        percentage_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        percentage_lbl.setText("0%");
        jPanel1.add(percentage_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 80, 20));

        ProgressBar.setBackground(new java.awt.Color(52, 50, 50));
        ProgressBar.setForeground(new java.awt.Color(72, 141, 188));
        ProgressBar.setBorder(null);
        ProgressBar.setBorderPainted(false);
        jPanel1.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 580, -1));

        randomtxt_lbl.setForeground(new java.awt.Color(230, 236, 239));
        randomtxt_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        randomtxt_lbl.setText("Loading");
        jPanel1.add(randomtxt_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 160, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Opticalog/Image/opticalog_logo_splash_screen.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        loading_lbl.setForeground(new java.awt.Color(230, 236, 239));
        loading_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loading_lbl.setText("Loading");
        jPanel1.add(loading_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 90, -1));

        version_lbl.setForeground(new java.awt.Color(230, 236, 239));
        version_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        version_lbl.setText("V.0.53 Release");
        jPanel1.add(version_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        setSize(new java.awt.Dimension(700, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel loading_lbl;
    public javax.swing.JLabel percentage_lbl;
    public javax.swing.JLabel randomtxt_lbl;
    public javax.swing.JLabel version_lbl;
    // End of variables declaration//GEN-END:variables
}
